app = "hooksdream"
primary_region = "sin"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "suspend"
  force_https = true
  internal_port = 8080
  min_machines_running = 1
  processes = ["app"]

  # Real-time optimizations
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  # Health checks for Socket.IO
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory = "2gb"
  memory_mb = 2048

# Metrics for monitoring
[metrics]
  port = 9091
  path = "/metrics"
