app = "hooksdream"
primary_region = "sin"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  # Prevent autostop for bot service
  auto_start_machines = true
  min_machines_running = 1    # Keep at least 1 machine running
  processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
